### ISSUE TITLE
Add a section for last years stats 

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/humblefoolcup#12]
Last year humble fool cup qualifiers https://www.codechef.com/HFCQ2016

**Comment by bhanu1911** [comment]
1. Sir what kind of design would you prefer for the table? 
2. Also, do you want to add only the top say 25 teams or do you need the entire table imported on the webpage? 
3. Does stats only include the questions or the entire details of last years' event? (e.g. Prize money etc.)

**Comment by gauthamzz** [comment]
We would like to have materializecss design.
Questions and last year participants count of first and second round would suffice.
Winners name should be also there

**Comment by bhanu1911** [comment]
SIr I'd like to take up this issue.

**Comment by magician03** [comment]
@bhanu1911 , yeah this issue is open,

- This needs to made as a separate page, not as a section of main page
-The color schema, has not yet been finalised, so you might need stay upon this issue during the pre production to modify the theme
- [Here](https://www.codechef.com/rankings/HFQC1601) is the ranklist of Humblefool cup finals. 
- Try to embed the ranklist-only if possible. or else wait for further notification from us.
- Strictly use materialise for css.
- navbar should be common with the main page.
- Share your progress regularly for us to assist you better.
- needs to be submitted within a week
- Stash all your commits into a single one.
- Make a separate file for `stats.html`.
- DO NOT modify the main `index.html` without asking us.

Follow these instructions carefully before proceeding. All the best! :smile: 

@bhanu1911 , has been assigned this issue. 

Cheers,
Diwakar

**Comment by magician03** [comment]
@bhanu1911 , please share your current progress.

**Comment by bhanu1911** [comment]
Sir, due to TriHacker Cup Round 2 and some personal commitments I was not able to do much, but I am learning materialize css right now. I will be ready with the stats.html page with all the basic stuff ready by tomorrow, and then if possible will integrate the ranklist as well.

**Comment by bhanu1911** [comment]
Sir, for the as-yet undecided color schema, can I use any random one for now? Or the same as humblefoolcup main website?

**Comment by magician03** [comment]
@bhanu1911 , Make it in sync with main site, do not use too much color at max 1/2 colours should be fine.

**Comment by magician03** [comment]
@bhanu1911 , I want a live progress or a demo of it ASAP !

**Comment by gauthamzz** [comment]
no one is currently working on this issue :+1: If anyone wants to try go ahead

**Comment by RavicharanN** [comment]
Can i work on this?
